#! /usr/bin/env bash

[ -z $1 ] && VOLUME="KEYCHAINS" || VOLUME="$1"
shift 1
[ -z $1 ] && VOLUMES_DIR="/Volumes" || VOLUMES_DIR="$1"

set -eo pipefail

if [ ! -d ~/.keychains ]; then
    echo "You have no keychains. The hidden directory ~/.keychains will be created for you in your home directory but you must place .keychain files you wish to backup into it yourself."
    mkdir -p ~/.keychains
    chmod 0700 ~/.keychains
    exit 0
fi

if [ ! -d ${VOLUMES_DIR}/${VOLUME} ]; then
    echo "Volume ${VOLUME} is not mounted. Please mount a volume named ${VOLUME} and try again."
    exit 1
fi

echo "Backing up keychains.."

rm -f ${VOLUMES_DIR}/${VOLUME}/keychain.tar.bz
tar -cvjf ${VOLUMES_DIR}/${VOLUME}/keychains.tar.bz ~/.keychains

echo -e "Done.\nEject volume ${VOLUME} if it is an external storage device and keep it safely stored."
