#! /usr/bin/env bash

[ -z $1 ] && VOLUME="KEYCHAINS" || VOLUME="$1"

set -eo pipefail

if [ ! -d ~/.keychains ]; then
    echo "You have no keychains. The hidden directory ~/.keychains will be created for you in your home directory but you must place your .keychain files into it yourself."
    mkdir -p ~/.keychains
    chmod 0700 ~/.keychains
    exit 0
fi

if [ ! -d /Volumes/${VOLUME} ]; then
    echo "Volume ${VOLUME} is not mounted. Please mount a volume named ${VOLUME} and try again."
    exit 1
fi

echo "Backing up keychains.."

rm -f /Volumes/${VOLUME}/keychain.tar.bz
tar -cvjf /Volumes/${VOLUME}/keychains.tar.bz ~/.keychains

echo "Done. Eject your USB key and keep it safe."
